### ISSUE TITLE
button state change should go to end of the long press duration value

### ISSUE THREAD

**Issue by autonome** [autonome/neverstop#10]
long press visual interaction was improved in #6, but the color change only occurs for a portion of the duration of the long press.

the color transition should occur fully over the entire duration of the long press.

**Comment by MBenz12** [comment]
fixed this issue in this [commit](https://github.com/autonome/neverstop/pull/9/commits/6139b8d17e86a3ffe509f3fe02c8adb6f9321f18)

**Comment by autonome** [comment]
confirmed, closing for now. will file followup w/ another small optimization.
