### ISSUE TITLE
button visual state change on long press should show progress

### ISSUE THREAD

**Issue by autonome** [autonome/neverstop#15]
current interaction slowly changes button color across a gradient from default color to red.

however, there are two ux issues  with this:

1. the press has couple ms of no visual response to click action

2. the user never has a visual indication of how long they must continue to press

let's try an alternate approach:

- animate the color of the button
- from left to right
- with a high contrast color (red maybe)
- for the duration of the press

**Comment by MBenz12** [comment]
implemented background like progress bar, not sure you like it

**Comment by autonome** [comment]
this is great, exactly what i was aiming for!

a couple of polish changes:

- remove rounded corners on background animating section, so it's a flat right side

- make it a constant time animation (no ease in/out)

**Comment by autonome** [comment]
I want to update colors as well, but not sure how yet and not a blocker. will file separate issue later for it.

**Comment by autonome** [comment]
fix is great, thanks!
