### ISSUE TITLE
long press should reset the timer

### ISSUE THREAD

**Issue by autonome** [autonome/neverstop#2]
currently, when you execute the stop action, the timer pauses. when you hit start, it begins from where it left off.

for now, the stop action should reset the timer to zero.

later, we'll figure out a pause/resume function, and how to integrate into the ux.

**Comment by MBenz12** [comment]
fixed this issue in this commit [3811139b5c4dc5e5d921185b03dd1c54866fc444](https://github.com/autonome/neverstop/commit/3811139b5c4dc5e5d921185b03dd1c54866fc444)

**Comment by autonome** [comment]
a bit abrupt, but works for now. i'll file followup issue w/ a refined design of this interaction.
