### ISSUE TITLE
manage recording w/ HK api instead of internal app timer

### ISSUE THREAD

**Issue by autonome** [autonome/neverstop#3]
api details here:

https://developer.apple.com/documentation/healthkit/workouts_and_activity_rings/running_workout_sessions

**Comment by MBenz12** [comment]
fixed this issue in this commit [7876e128fdf30559e0b0afa1ab2820a9b0439384](https://github.com/autonome/neverstop/commit/7876e128fdf30559e0b0afa1ab2820a9b0439384)

**Comment by autonome** [comment]
i haven't been able to figure out how to get Activity or Workouts apps on watchOS simulator, but confirmed the recordings show up as "workouts" in the Health app.
