### ISSUE TITLE
button should be even larger

### ISSUE THREAD

**Issue by autonome** [autonome/neverstop#4]
both vertically and horizontally

needs to be a megabutton.

try 50% of screen height for height and 80% of screen for width.

eg something like below.

![neverstop run recorder](https://github.com/autonome/neverstop/assets/50103/695fb7b5-3b6f-4a52-ada1-e4c7b90d397a)

likely we'll later play with things like customized and more detailed display above the button. but for for now, this is fine.

**Comment by MBenz12** [comment]
fixed this issue in this commit [3811139b5c4dc5e5d921185b03dd1c54866fc444](https://github.com/autonome/neverstop/commit/3811139b5c4dc5e5d921185b03dd1c54866fc444)
