### ISSUE TITLE
permissions audit

### ISSUE THREAD

**Issue by autonome** [autonome/neverstop#5]
@MBenz12 currently there's one write permission and a set of read permissions requested on first run.

Are all these required? The cycling one seems unnecessary at this point, let's focus just on run recording, for mvp. We can add more later.

What happens if user says no?

**Comment by MBenz12** [comment]
fixed this issue in this [commit ](https://github.com/autonome/neverstop/commit/d624916cdd92f189855b94c0b38fda0b34d28617).
if user says no, user can't start to record workout.
