### ISSUE TITLE
button needs visual state change when pressed and released

### ISSUE THREAD

**Issue by autonome** [autonome/neverstop#6]
when starting a recording, the text of the button changes. it's ok, but not ideal.

when holding the button to stop the recording, there's no visual feedback at all.

should add a visual indication of button press which covers both interactions.

i see you're using a text view for this currently. any reason not to use the native Button for this?

**Comment by autonome** [comment]
an idea for future: animate the button from right to left during the long press.

**Comment by autonome** [comment]
another effect that might be cool is to flip the background and button color. this would be quite clear that the press occurred.

or could do the animation noted above, but on the background color. this also would  be very visible even in conditions of duress during a workout.

**Comment by MBenz12** [comment]
fixed this issue in this [commit](https://github.com/autonome/neverstop/commit/c0d4b3a5905e7f29d8869a5c0750c42d5743f5ff).
capturing long press gesture on native button is not working, instead on text it's working

**Comment by autonome** [comment]
this looks great, mostly there. i'll file new issue for a small improvement.
