### ISSUE TITLE
improve the experience of stopping a recording

### ISSUE THREAD

**Issue by autonome** [autonome/neverstop#8]
The hyperminimal version of this would be to reset the elapsed time to 00:00.

But ideally there's a visual indication that the recording was saved at the OS level, giving the user comfort and assurance that it was correctly recorded via Healthkit.

One way to do this could be to have a "recording complete" screen, with the elapsed time of the run, and an icon and button/link to open the recording in the official Workout app.

**Comment by MBenz12** [comment]
fixed this issue in this [commit](https://github.com/autonome/neverstop/pull/9/commits/076d2277109965252ae9272f38be873fcb19d036)

**Comment by autonome** [comment]
new flow is great, even cleaner than original suggestion
